config/routes.rb
Rails.application.routes.draw do
  match '*path' => 'examinees#create', via: :options
  root to: 'statics#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :examinees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/examinee.rb
class Examinee < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, allow_blank: true, presence:true, length: { in: 8..50 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def correct_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to root_url
    end
  end

  def save_last_user
    if User.all.length < 2
      flash[:danger] = '管理者は1人以上必要です'
      redirect_to root_url
    end
  end

  def flush_old_record
    if Examinee.all.length > 5000
      Examinee.first.destroy
    end
  end
end

app/controllers/examinees_controller.rb
class ExamineesController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :flush_old_record, only: [:create]

  def index
    @examinees = Examinee.all.page(params[:page])
  end

  def show
    @examinee = Examinee.find(params[:id])
  end

  def create
    @examinee = Examinee.new(examinee_params)
    respond_to do |format|
      if @examinee.save
        format.json { render json: 'ok!', status: :created }
      else
        format.json { render json: 'ng!', status: :unprocessable_entity }
      end
    end
  end

  private

  def examinee_params
    params.require(:examinee).permit(
      :name, :time_1, :time_2, :time_3, :time_4, :time_5, :time_total,
      :miss_1, :miss_2, :miss_3, :miss_4, :miss_5, :miss_total,
      :ratio_1, :ratio_2, :ratio_3, :ratio_4, :ratio_5, :ratio_total
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインできませんでした'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in
  before_action :save_last_user, only: [:destroy]

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(name: 'User' + DateTime.now.to_i.to_s)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      redirect_to root_path
    else
      flash.now[:danger] = '入力に誤りがあります。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to @user
    else
      flash.now[:danger] = '入力に誤りがあります'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examinees_helper.rb
module ExamineesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/examinees/index.html.erb
<div class="text-center">
  <h1>テスト結果一覧</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= paginate @examinees %>
    <table border="2px solid" style="width:100%;">
      <tr>
        <td>テスト日時</td>
        <td>名前</td>
        <td>合計テスト時間</td>
        <td>合計ミス回数</td>
        <td>正答率</td>
      </tr>
      <% @examinees.each do |examinee| %>
        <tr>
          <td><%= examinee.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></td>
          <td><%= link_to examinee.name, examinee %></td>
          <td><%= examinee.time_total %>秒</td>
          <td><%= examinee.miss_total %>回</td>
          <td><%= examinee.ratio_total %>%</td>
        </tr>
      <% end %>
    </table>
    <%= paginate @examinees %>
  </div>
</div>

app/views/examinees/show.html.erb
<div class="text-center">
  <h1>テスト結果詳細</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table border="2px solid" style="width:100%;">
      <tr>
        <td>テスト日時</td>
        <td><%= @examinee.created_at.strftime("%Y年 %m月 %d日 %H:%M")  %></td>
      </tr>
      <tr>
        <td>名前</td>
        <td><%= @examinee.name %></td>
      </tr>
      <tr>
        <td>1回目テスト時間</td>
        <td><%= @examinee.time_1 %>秒</td>
      </tr>
      <tr>
        <td>2回目テスト時間</td>
        <td><%= @examinee.time_2 %>秒</td>
      </tr>
      <tr>
        <td>3回目テスト時間</td>
        <td><%= @examinee.time_3 %>秒</td>
      </tr>
      <tr>
        <td>4回目テスト時間</td>
        <td><%= @examinee.time_4 %>秒</td>
      </tr>
      <tr>
        <td>5回目テスト時間</td>
        <td><%= @examinee.time_5 %>秒</td>
      </tr>
      <tr>
        <td>1回目ミス回数</td>
        <td><%= @examinee.miss_1 %>回</td>
      </tr>
      <tr>
        <td>2回目ミス回数</td>
        <td><%= @examinee.miss_2 %>回</td>
      </tr>
      <tr>
        <td>3回目ミス回数</td>
        <td><%= @examinee.miss_3 %>回</td>
      </tr>
      <tr>
        <td>4回目ミス回数</td>
        <td><%= @examinee.miss_4 %>回</td>
      </tr>
      <tr>
        <td>5回目ミス回数</td>
        <td><%= @examinee.miss_5 %>回</td>
      </tr>
      <tr>
        <td>1回目正答率</td>
        <td><%= @examinee.ratio_1 %>%</td>
      </tr>
      <tr>
        <td>2回目正答率</td>
        <td><%= @examinee.ratio_2 %>%</td>
      </tr>
      <tr>
        <td>3回目正答率</td>
        <td><%= @examinee.ratio_3 %>%</td>
      </tr>
      <tr>
        <td>4回目正答率</td>
        <td><%= @examinee.ratio_4 %>%</td>
      </tr>
      <tr>
        <td>5回目正答率</td>
        <td><%= @examinee.ratio_5 %>%</td>
      </tr>
      <tr>
        <td>合計テスト時間</td>
        <td><%= @examinee.time_total %>秒</td>
      </tr>
      <tr>
        <td>合計ミス回数</td>
        <td><%= @examinee.miss_total %>回</td>
      </tr>
      <tr>
        <td>合計正答率</td>
        <td><%= @examinee.ratio_total %>%</td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">採用テスト管理ページ</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right navbar-ul">
          <% if logged_in? %>
            <li><%= link_to 'HOME', root_path %></li>
            <li><%= link_to 'テスト結果一覧', examinees_path %></li>
            <li><%= link_to '管理者情報一覧', users_path %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'HOME', root_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>採用テスト管理ページ</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" id="application-container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/statics/index.html.erb
<h1>採用テスト管理ページ</h1>

app/views/users/_form.html.erb
<div class="form-group">
  <%= f.label :name, '管理者名' %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email, 'メールアドレス' %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password, 'パスワード' %>
  <%= f.password_field :password, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation, '確認パスワード' %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>管理者情報編集</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <%= render 'layouts/error_messages', model: f.object %>

      <%= render 'users/form', f: f %>

      <%= f.submit '更新', class: 'btn btn-primary btn-block' %>
    <% end %>
    <div data-turbolinks="false" class="return">
      <%= link_to '管理者情報へ戻る', @user, class: 'btn btn-warning btn-block' %>
      <%= link_to 'トップページへ戻る', root_path, class: 'btn btn-warning btn-block' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="text-center">
  <h1>管理者情報一覧</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= paginate @users %>
    <% @users.each do |user| %>
      <div><%= link_to user.name, user %></div>
    <% end %>
    <%= paginate @users %>
    <%= link_to '新規管理者登録', new_user_path, class: 'btn btn-info btn-block' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規管理者登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <%= render 'layouts/error_messages', model: f.object %>

      <%= render 'users/form', f: f %>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
    <div data-turbolinks="false" class="return">
      <%= link_to '管理者情報一覧へ戻る', users_path, class: 'btn btn-warning btn-block' %>
      <%= link_to 'トップページへ戻る', root_path, class: 'btn btn-warning btn-block' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1>管理者情報</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div>管理者名：<%= @user.name %></div>
    <div>メールアドレス：<%= @user.email %></div>
    <%= link_to '編集', edit_user_path(@user), class: 'btn btn-success btn-block' %>
    <%= link_to '削除', @user, method: :delete, data: {confirm: '管理者を削除しますか？'}, class: 'btn btn-danger btn-block' %>
    
    <div data-turbolinks="false" class="return">
      <%= link_to 'トップページへ戻る', root_path, class: 'btn btn-warning btn-block' %>
    </div>
  </div>
</div>